version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: "/numerix-app/docker-credentials/username"
    DOCKER_PASSWORD: "/numerix-app/docker-credentials/password"
    DOCKER_URL: "/numerix-app/docker-registry/url"

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_URL"
      - IMAGE_TAG="$CODEBUILD_BUILD_NUMBER"
      - IMAGE_NAME="simple-python-flask-app"
      - REPO="$DOCKER_USERNAME/$IMAGE_NAME"
      - echo "Building and pushing $REPO:$IMAGE_TAG"
      - docker build -t "$REPO:$IMAGE_TAG" .
      - docker push "$REPO:$IMAGE_TAG"

  post_build:
    commands:
      - echo "Build and push completed successfully!"
      - echo "Listing all files in current directory:"
      - ls -la
      - echo "Checking if scripts exist:"
      - ls -la *.sh || echo "No .sh files found"
      - echo "Contents of artifact directory:"
      - find . -name "*.sh" -type f

artifacts:
  files:
    - "appspec.yml"
    - "stop_container.sh"
    - "start_container.sh"
    - "**/*"
  base-directory: ./
