version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Setting up integration test environment..."
      - pip install -r requirements.txt || true  # Simulate install

  pre_build:
    commands:
      - echo "Preparing integration tests..."

  build:
    commands:
      - echo "Running integration tests..."
      - echo "PASS" > integration_test_result.txt
      - cat integration_test_result.txt

      # Optional: Uncomment below lines to simulate failure
      # - |
      #     if grep -qv "PASS" integration_test_result.txt; then
      #       echo "❌ Integration Tests Failed. Failing the build."
      #       exit 1
      #     else
      #       echo "✅ Integration Tests Passed"
      #     fi

artifacts:
  files:
    - integration_test_result.txt
