version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - pytest tests/unit --junitxml=results.xml

reports:
  unit-tests:
    files:
      - results.xml
    file-format: JUNITXML
